import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Expense } from '../models/expense.model';
import { ExpensesService } from '../services/expenses.service';

@Component({
  selector: 'add-expense',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './add-expense.component.html',
  styleUrl: './add-expense.component.css',
})
export class AddExpenseComponent {
  name!: string;
  type!: string;
  amount!: number;
  //attachment!: File | null;

  constructor(private expensesService: ExpensesService) {
    this.initForm();
  }

  initForm() {
    this.name = '';
    this.type = '';
    this.amount = 0;
    // this.attachment = null;
  }

  submit() {
    // add expense
    if (this.name && this.type) {
      const newExpense: Expense = {
        id: 0, // generated by service
        name: this.name,
        type: this.type,
        amount: this.amount,
        //attachment: this.attachment?.name ?? null, // TODO: implement saving to BE
      };

      this.expensesService.addExpense(newExpense);

      // clear form
      this.initForm();
    }
  }

  // selectFile(event: any) {
  //   this.attachment = event.target.files[0];
  // }
}
